/*
Copyright 2023 Upbound Inc. - ANKASOFT
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha11 "github.com/avarei/provider-vra/v2/apis/cluster/machine/v1alpha1"
	v1alpha1 "github.com/avarei/provider-vra/v2/apis/cluster/project/v1alpha1"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this LoadBalancer.
func (mg *LoadBalancer) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &v1alpha1.ProjectList{},
			Managed: &v1alpha1.Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Targets); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Targets[i3].MachineID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Targets[i3].MachineIDRef,
			Selector:     mg.Spec.ForProvider.Targets[i3].MachineIDSelector,
			To: reference.To{
				List:    &v1alpha11.MachineList{},
				Managed: &v1alpha11.Machine{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Targets[i3].MachineID")
		}
		mg.Spec.ForProvider.Targets[i3].MachineID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Targets[i3].MachineIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &v1alpha1.ProjectList{},
			Managed: &v1alpha1.Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.Targets); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Targets[i3].MachineID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Targets[i3].MachineIDRef,
			Selector:     mg.Spec.InitProvider.Targets[i3].MachineIDSelector,
			To: reference.To{
				List:    &v1alpha11.MachineList{},
				Managed: &v1alpha11.Machine{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Targets[i3].MachineID")
		}
		mg.Spec.InitProvider.Targets[i3].MachineID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Targets[i3].MachineIDRef = rsp.ResolvedReference

	}

	return nil
}
