apiVersion: network.crossplane.io/v1alpha1
kind: NetworkProfile
metadata:
  name: test-network-profile-4
spec:
  forProvider:
    name: 'test-network-profile-4'
    description: 'test-network-profile-4'
    regionId: ''
    projectIdRef:
      name: 'test-project-2'
  providerConfigRef:
    name: vra-test
