apiVersion: contentsource.crossplane.io/v1alpha1
kind: ContentSource
metadata:
  name: test-content-source-4
spec:
  forProvider:
    name: 'test-content-source-4'
    description: 'test-content-source-4'
    syncEnabled: false
    config: 
    - path: 'test-blueprint-2'
      projectName: 'master'
      repository:  'vracontent/vra8_content_source_test'
      integrationId: var.integration_id
    typeId: 'com.gitlab'
    projectIdRef:
      name: 'test-project-2'
    

  providerConfigRef:
    name: vra-test
