name: vmware/vra
resources:
  VMware vRA Resource - terraform-provider-vra:
    subCategory: VMware vRA
    description: Official documentation https://registry.terraform.io/providers/vmware/vra/latest/docs
    name: VMware vRA Resource - terraform-provider-vra
    title: VMware vRA Resource - terraform-provider-vra
    argumentDocs: {}
    importStatements: []
