/*
Copyright 2023 Upbound Inc. - ANKASOFT
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AccountAws) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AccountAzure) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AccountGCP) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AccountNsxt) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AccountVmc) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AccountVsphere) Hub() {}
