/*
Copyright 2023 Upbound Inc. - ANKASOFT
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Profile) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProfileAws) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProfileAzure) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProfileVsphere) Hub() {}
