name: Tag

on:
  workflow_dispatch: 
    inputs:
      version:
        description: 'Release version (e.g. v0.1.0)'
        required: true
      message:
        description: 'Tag message'
        required: true

jobs:
  tag:
    uses: upbound/official-providers-ci/.github/workflows/provider-tag.yml@v0.12.1
    with:
      version: ${{ github.event.inputs.version }}
      message: ${{ github.event.inputs.message }}
