name: Tag

on:
  workflow_dispatch: 
    inputs:
      version:
        description: 'Release version (e.g. v0.1.0)'
        required: true
      channel:
        description: 'Release channel'
        required: true
        type: choice
        default: main
        options:
          - main
          - alpha
          - beta
          - stable
jobs:
  tag:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Fetch History
        run: git fetch --prune --unshallow

      - name: Publish Artifacts
        run: make tag VERSION=${{ inputs.version }} CHANNEL=${{ inputs.channel }}
